version: '2'
       
services: 
    nginx_local:
        image: nginx
        restart: always
        ports:
            - "8080:80"
        working_dir: /var/www
        volumes:
            - ./code:/var/www
            - ./conf/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php_local

    php_local: 
        image: phalconphp/php-fpm
        restart: always
        ports:
            - "8000:80"
        working_dir: /var/www
        volumes:
            - ./code:/var/www
            # - ./conf/nginx/config-php.ini:/usr/local/etc/php/conf.d/php.ini
        depends_on:
            - mysql_local
        # hostname: webserver
        
    mysql_local:
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            #- variables.env
        volumes:
           - ./dbdata/nginx_sql:/var/lib/mysql
        # volumes:
        #     - ./data/mysql:/docker-entrypoint-initdb.d
        # networks:
        #     - back-tier

   
# networks:
#     back-tier:
